; A throwaway installer that exists only to look at the chrome.
;
; The real one is generated by Tauri from src-tauri/installer/installer.nsi and
; takes a full `tauri build` to produce. This includes the same theme.nsh and
; lays out the same three pages, so it compiles in a couple of seconds and can
; be run over and over while adjusting the design.
;
; It installs nothing: the pages are real, the work behind them is a stub.
;
;   powershell -File scripts/preview-installer.ps1

Unicode true
ManifestDPIAware true
ManifestDPIAwareness PerMonitorV2

!include MUI2.nsh

!define IB_ROOT "${__FILEDIR__}\.."
!define IB_INSTALLER "${IB_ROOT}\src-tauri\installer"

Name "Hangar.AI"
OutFile "${IB_OUTFILE}"
InstallDir "$LOCALAPPDATA\Hangar.AI"
RequestExecutionLevel user

!define MUI_ICON "${IB_ROOT}\src-tauri\icons\icon.ico"

!include "${IB_INSTALLER}\theme.nsh"

Page custom ibWelcomePage
!define MUI_PAGE_CUSTOMFUNCTION_SHOW ibInstallPageShow
!insertmacro MUI_PAGE_INSTFILES
Page custom ibFinishPage

!insertmacro MUI_LANGUAGE "English"

Function .onInit
  !insertmacro IB_ExtractAssets
FunctionEnd

Function ibNext
  SendMessage $HWNDPARENT ${WM_COMMAND} 1 0
FunctionEnd

Function ibQuit
  SendMessage $HWNDPARENT ${WM_COMMAND} 2 0
FunctionEnd

Function ibWelcomePage
  nsDialogs::Create 1018
  Pop $IB_Dialog
  ${If} $IB_Dialog == error
    Abort
  ${EndIf}

  !insertmacro IB_Backdrop
  !insertmacro IB_Masthead "Hangar.AI" "A terminal multiplexer for CLI coding agents"
  !insertmacro IB_CloseButton ibQuit
  !insertmacro IB_Button $IB_Primary 160 240 200 44 "Install"
  ${NSD_OnClick} $IB_Primary ibNext
  !insertmacro IB_Label $IB_Note 40 298 440 20 "$INSTDIR" dim

  nsDialogs::Show
FunctionEnd

Function ibInstallPageShow
  !insertmacro IB_StyleInstallPage "Hangar.AI" "A terminal multiplexer for CLI coding agents" "Installing…"
FunctionEnd

Function ibFinishPage
  nsDialogs::Create 1018
  Pop $IB_Dialog
  ${If} $IB_Dialog == error
    Abort
  ${EndIf}

  !insertmacro IB_Backdrop
  !insertmacro IB_Masthead "Hangar.AI" "A terminal multiplexer for CLI coding agents"
  !insertmacro IB_CloseButton ibNext
  !insertmacro IB_Label $IB_Note 40 240 440 22 "Hangar.AI is installed" ""
  !insertmacro IB_Button $IB_Primary 160 276 200 44 "Launch Hangar.AI"
  ${NSD_OnClick} $IB_Primary ibNext

  nsDialogs::Show
FunctionEnd

; Paced so the progress bar and the status line are actually visible.
Section "Install"
  SetOutPath "$PLUGINSDIR"
  SetAutoClose true
  DetailPrint "Preparing Hangar.AI 0.3.0"
  Sleep 500
  DetailPrint "Extracting hangar-ai.exe"
  Sleep 900
  DetailPrint "Extracting the WebView2 loader"
  Sleep 700
  DetailPrint "Registering the MCP server"
  Sleep 700
  DetailPrint "Creating shortcuts"
  Sleep 600
SectionEnd
